baseurl = "https://vmwong.net"
languageCode = "en-US"
title = "Vincent Wong"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "temp_pic.jpg"
  author = "Vincent Wong"
  description = "Professional Website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "vincentmwong"
  Email         = "vmwong@indiana.edu"
  LinkedIn      = "vincentmwong"

## Main Menu
[menu]
    [[menu.main]]
    name = "Projects"
    weight = 9
    identifier = "projects"
    url = "/projects/"

    [[menu.main]]
    name = "Publications"
    weight = 8
    identifier = "publications"
    url = "/publications/publications/"

    [[menu.main]]
    name = "Resume"
    weight = 7
    identifier = "resume"
    url = "/wong_cv.pdf/"

    [[menu.main]]
    name = "Music"
    weight = 6
    identifier = "music"
    url = "/music/"